// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD148lHPXn-l1x_tiE3RUoEhlcbSwKGzRg',
    appId: '1:111328080618:web:79087e2c1046d88d0ddd93',
    messagingSenderId: '111328080618',
    projectId: 'bicitrack-de168',
    authDomain: 'bicitrack-de168.firebaseapp.com',
    storageBucket: 'bicitrack-de168.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq42MYfaeWmDOHZYHEML4DLrpVOYkPDiw',
    appId: '1:111328080618:android:3068d14d4678014f0ddd93',
    messagingSenderId: '111328080618',
    projectId: 'bicitrack-de168',
    storageBucket: 'bicitrack-de168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxEx-TC1nIkM1Udm1MvFEOlvk471CTW54',
    appId: '1:111328080618:ios:cfb8dfbd7615ab6c0ddd93',
    messagingSenderId: '111328080618',
    projectId: 'bicitrack-de168',
    storageBucket: 'bicitrack-de168.appspot.com',
    iosBundleId: 'com.example.bicitrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxEx-TC1nIkM1Udm1MvFEOlvk471CTW54',
    appId: '1:111328080618:ios:b3a27b011ac010f40ddd93',
    messagingSenderId: '111328080618',
    projectId: 'bicitrack-de168',
    storageBucket: 'bicitrack-de168.appspot.com',
    iosBundleId: 'com.example.bicitrack.RunnerTests',
  );
}
